### ISSUE TITLE
update factory contract

### ISSUE THREAD

**Issue by Ucheokolo** [Nonnyjoe/MEDISYNC#9]
Create a function in the factory contract to make a call to registerHospital function in the patients_record contract. it takes the registered hospital address and sets it to true in a mapping function.

**Comment by Nonnyjoe** [comment]
Nice observation @Ucheokolo, but at this moment the patient_record contract lacks a function implementation to call. also the call can be made on creation of a new hospital and not as a stand alone function. what do you think about this, @Ucheokolo  and @Ginika-Chinonso ??
